import Footer from "@/components/footer/Footer";
import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import Nav from "./Nav/Nav";
import "./globals.css";

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hauteside",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <div className={`${font.className} min-h-screen`}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
